### ISSUE TITLE
Improve performance of the libzim version

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#767] opened 2021-10-29 16:20 UTC
Currently, the performance of the libzim version of kiwix-js is worse than the plain javascript version, although the ZIM accesses are much faster with libzim (compiled in wasm).

After adding some timers in the code, we found that it comes from the fact that the WebWorker requested by the emscripten build is mono-threaded : all calls are enqueued and handled one after the other one.

There is almost no overhead of copying the Array in the WebWorker (to have a transferable object).

I currently don't see any other idea than using a pool of WebWorkers instead of only one. It would increase the memory usage because each one would hold its own instance of libzim (with its own cache etc). I don't see how to have a single instance of libzim shared among several WebWorkers for now

We might technically use the libzim directly in the ServiceWorker, instead of a WebWorker. But we can't access the files from the ServiceWorker

**Comment by Jaifroid** [comment] 2022-12-05 07:37
We may have to look for a different WASM File System if the disabling of `SharedArrayBuffer` goes ahead in Chrome. See https://github.com/openzim/javascript-libzim/issues/22.

**Comment by kelson42** [comment] 2023-01-09 18:12
Seems to me this ticket belongs to repository `openzim/javascript-libzim`.

**Comment by Jaifroid** [comment] 2023-01-09 18:25
Yes, it's the "same" issue (sort of) that I've been struggling with in https://github.com/openzim/javascript-libzim/issues/42. The problem is that mossroy's suggestion of a pool of Web workers won't help with the issue I identified there, i.e. that the file takes a very long time to load on (probably) ARM-based systems, or on systems with slow I/O. Closing in favour of that issue, but will copy mossroy's comment there.

**Closed by Jaifroid** 2023-01-09 18:25 UTC
Labels: backend
