### ISSUE TITLE
Can Kiwix remember user settings of Dark theme?

### ISSUE THREAD

**Issue by alextooter** [kiwix/kiwix-js#612] opened 2020-04-04 08:42 UTC
I like the Dark theme in v2.7,it's beautiful.After I close Kiwix page,then reopen it,Kiwix not remember my choose of Dark theme.

Can we store this option in somewhere,don't let me choose everytime?

**Comment by Jaifroid** [comment] 2020-04-04 08:43
Hi @alextooter, it should be able to. Which platform are you using, so I can trobuleshoot?

**Comment by alextooter** [comment] 2020-04-04 08:50
> Hi @alextooter, it should be able to. Which platform are you using, so I can trobuleshoot?
I am using macOS 10.15.4,Firefox 74.0.1,kiwix 2.7.0
My way of using kiwix:click the icon on toolbar,kiwix open with light theme,then I choose Dark+invert(wikimedia*),it turn to dark theme.Close this tab,open it,using Light theme again.

**Comment by Jaifroid** [comment] 2020-04-04 09:06
OK, thanks, @alextooter . I presume that's in the Firefox extension?

**Comment by Jaifroid** [comment] 2020-04-04 09:13
@alextooter I reproduce the bug in Firefox Extension on Windows 10. However, it is not just with this feature, it is with any feature that stores its settings in a cookie. Something must have been deprecated. Very sorry not to have picked this up in testing.

@mossroy can you reproduce? In the Firefox extension, try changing any setting in Config that should persist between tab sessions, and they are lost the next time the Kiwix JS tab is opened.

**Comment by Jaifroid** [comment] 2020-04-04 11:24
Proof that cookies are disabled in Firefox browser extension:

In the extension tab devtools type `document.cookie="username=John Doe"` and then `document.cookie` Result:

![image](https://user-images.githubusercontent.com/4304337/78437020-b433df80-766e-11ea-8ccd-dc844aab6ee2.png)

In a normal tab opening `file:///.../kiwix-js/www/index.html`:

![image](https://user-images.githubusercontent.com/4304337/78438036-fe1cc580-766e-11ea-8437-43337b9ef247.png)

**Comment by Jaifroid** [comment] 2020-04-04 12:45
Looking at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Work_with_the_Cookies_API, I see we should have a `permissions` entry in our `manifest.json` to use the Cookies API in Firefox Extensions:

![image](https://user-images.githubusercontent.com/4304337/78450980-75a42200-767a-11ea-80b4-fb3be07f5c47.png)

We don't have this.

**Comment by mossroy** [comment] 2020-04-04 15:06
I reproduce this issue with Firefox 74 (on Ubuntu), not on Chromium 80. I also reproduce on Firefox 68.6 ESR (on Windows 8.1).
So this seems to be Firefox-specific.
Adding 

    "permissions": [
        "tabs",
        "cookies",
        "<all_urls>"
    ],

in manifest.json does not help : it seems to be a permission to access cookies from other tabs/websites

**Comment by Jaifroid** [comment] 2020-04-04 15:47
I suggest a possible solution to this in #613 .

**Comment by mossroy** [comment] 2020-04-04 17:03
Based on https://bugzilla.mozilla.org/show_bug.cgi?id=1418961#c6 , it seems to be the expected behavior in Firefox extensions : 

> Cookies are only supported in HTTP documents

So we'll have to find another way to store the user preferences. I'll have a look at #613

**Comment by Jaifroid** [comment] 2020-04-04 17:06
OK. It seems this is since 55/56! I guess our users generally didn't change the defaults, then!

**Comment by mossroy** [comment] 2020-04-04 17:16
It's not that surprising : in Firefox extension, you can not use SW mode, so this setting can not be changed. And the theme and cache settings are recent. So the only setting that could be affected since a long time is the "Permanently hide active content warning"

**Comment by Jaifroid** [comment] 2020-04-14 15:42
@alextooter We are about to merge into master a fix for this issue that works in development testing on Firefox extension and that we very much hope will work in production. Please note that you will have to wait for a new release, which may take some time as we usually accumulate a number of features before making a new release.

**Closed** 2020-04-14 15:45 UTC
Labels: bug
