### ISSUE TITLE
PhET zim not read on Kiwix-JS

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-js#339] opened 2018-01-31 18:11 UTC
I basically get the splash screen and that's it - no way to access content (either Kiwix JS windows or browser extension). See image:
![phet](https://user-images.githubusercontent.com/21675885/35639344-2cc641fa-0677-11e8-8fe2-4a03e0915a20.png)

**Comment by mossroy** [comment] 2018-01-31 18:43
This is a known issue. Kiwix-js does not currently inject the javascript files at all.
It was causing issues in the browser engine (but it was a long time ago, so maybe this could be tested again).
See #152 .
Anyway, I don't know if enabling javascript would be enough to make PhET files work. There might be other contents that are not well supported by kiwix-js.

**Comment by Popolechien** [comment] 2018-01-31 18:50
Ok thanks -  I'd seen #152 but wasn't entirely sure it was the same problem.

**Comment by mossroy** [comment] 2018-01-31 18:56
To be honest, I'm not 100% sure either. But I don't see how these PhET experiments would work without a bunch of javascript code, so I did not investigate more.

**Comment by mossroy** [comment] 2018-11-14 15:09
Javascript is now enabled in ServiceWorker mode. PhET seems to work properly in this mode.

**Comment by kelson42** [comment] 2018-11-18 16:03
@mossroy I have tried with last nightly and https://download.kiwix.org/zim/phet/phet_fr_2018-11.zim. The welcome page is empty = not displayed properly to me. I'm in Jquery mode as service worker does not work out-of-the-box on FF.

**Comment by Jaifroid** [comment] 2018-11-18 16:11
@kelson42 In master, only SW mode currently supports PhET. I have an experimental branch, [JavaScript Support](https://github.com/kiwix/kiwix-js/tree/javaScript-support) that include JS support in jQuery mode. However, the front page of PhET is not currently working in that branch in jQuery mode. If you press the random button in that branch, you'll see that a random experiment will load and is usable. But I need to debug the landing page. It's probably because it uses ReactJS (I think), and that involves a lot of inline JavaScript, which my branch tries to put into attached scripts so that a page will work with as restrictive CSP. I may have to ditch that workaround.

**Comment by mossroy** [comment] 2018-11-18 16:36
In ServiceWorker mode, the latest gutenberg seems to work well too, and also various ZIMs that have videos (tedx, oer4schools, dirtybiology etc, even if moving to a specific time in the video does not work on all browsers)

**Comment by Jaifroid** [comment] 2018-11-20 08:57
I can get the PhET UI to show up in jQuery mode in my JS support branch if I disable the code that searches for `<script>…</script>` blocks, and replaces them with blob scripts. The problem is that some script blocks are in fact React JSX templates, and these clearly need to be left in place. I can exclude script blocks of type `text/html` form the replacement.

However, it is still not possible (yet) to launch titles from this UI because we would need to patch the JavaScript that references the ZIM url, so that it launches the extraction engine. This looks pretty difficult to do. However, if we can get our standard search to work correctly in these ZIMs (#440), it would mitigate this problem.

**Comment by Jaifroid** [comment] 2020-03-04 14:11
PhET is now supported in Service Worker mode, and a banner is thrown up in jQuery mode asking the user to switch (and showing how). I do have an experimental branch that injects JS in jQuery mode, and it can run PhET experiments, but it can't run the React-based UI. In any case, this issue is a specific case of #152 , and that issue would be the place to solve it if it's worthwhile merging my version that enables injection of JavaScript from the ZIM. So I'm closing this (though feel free to re-open if it needs further discussion here).

**Closed by Jaifroid** 2020-03-04 14:11 UTC
Labels: bug
