### ISSUE TITLE
Have a fancy library

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js#846] opened 2022-02-13 11:13 UTC
Now that we have a nice looking https://library.kiwix.org with and OPDS API. I would propose that Kiwix JS provides a nicer solution to download ZIM files. Maybe just load https://library.kiwix.org for example?

**Comment by mossroy** [comment] 2022-03-02 14:03
> Maybe just load https://library.kiwix.org for example?

I don't see what you mean by that.

Is this a duplicate of #114 ?

So far, we did not implement anything to download ZIM files in kiwix-js, but @Jaifroid did in kiwix-js-windows. I suppose you mean his implementation could now be improved with OPDS?

**Comment by kelson42** [comment] 2022-03-02 18:14
@mossroy I don't know how the final solution should look like... but AFAIK everything is there now to avoid using https://download.kiwix.org.

**Comment by Jaifroid** [comment] 2022-03-02 20:31
I think we should develop a modern version here in Kiwix JS using the new system, and then I could backport it to Kiwix JS Windows. The implementation I have in KJSW is currently very different. It's fast and gets the job done (offers mirrors and torrent files), but it is text-based, not so pretty.

**Comment by Jaifroid** [comment] 2022-06-12 09:30
JFYI I now offer a link to preview the chosen ZIM on library.kiwix.org in the download UI in KJSW. This is an interim measure.

A simple option to trial here would be to load download.kiwix.org in an iframe when the user requests opening the Archive Library in-app. That would "just work" I think. Would we want something more complex, i.e. using OPDS ourselves and and offering a slimmed-down UI?

I don't think we need to manage downloads ourselves, as browsers all have their own sophisticated code for doing this, and nothing we could do would have the same level of FS access (only in Chromium browsers could we use the File System Access API).

**Comment by Jaifroid** [comment] 2022-06-12 09:32
PS Advantage of using browser to manage downloads is that downloads can continue in the background even if the app is closed.

**Comment by kelson42** [comment] 2022-06-12 12:20
BTW you might be interested in this new feature to be developed this summer https://github.com/kiwix/libkiwix/issues/585

**Comment by kelson42** [comment] 2023-01-09 20:40
Highly related to #489, to do this ticket either getting OPDS and building UI locally or just getting the HTML directly from library.kiwix.org.

**Comment by Jaifroid** [comment] 2023-01-09 20:57
My comment https://github.com/kiwix/kiwix-js/issues/846#issuecomment-1153113297 is still my opinion. This wouldn't be hard, just needs.... free time!

**Closed** 2023-10-09 19:15 UTC
Labels: enhancement, user interface
