### ISSUE TITLE
Equations are not rendered correctly

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-js#308] opened 2017-11-21 13:28 UTC
The issue arose both under Firefox and Chrome: equations (labeled under <math> markup on mediawiki) are not rendered correctly. I don't know if this is related to issue #297, but here we go:

![capture d ecran 2017-11-21 a 14 26 13](https://user-images.githubusercontent.com/21675885/33074932-318a0956-cec8-11e7-8ef6-6944ab25954e.png)

**Comment by Popolechien** [comment] 2017-11-21 15:39
test was run on newly-created Maths zim [http://download.kiwix.org/zim/wikipedia/wikipedia_en_maths_nopic_2017-11.zim](http://download.kiwix.org/zim/wikipedia/wikipedia_en_maths_nopic_2017-11.zim)

Tested on Android, works fine.

**Comment by Jaifroid** [comment] 2017-12-07 06:50
This is caused by #278 and #297. The slow, memory-intensive decompression required to extract SVGs causes a memory overflow issue on pages with more than a few equations (see Trignometry or Sine). This crashes the extraction engine in all browsers except, occasionally, Chrome, which nevertheless really struggles.

In Kiwix-JS-Windows, I worked around this by decompressing the images in carefully controlled batches of no more than three at a time, as the user scrolls down the page, so this article renders fine there (see below). The other solution I implemented was to typeset maths equations using MathJax, and this allows lightening-fast rendering of pages such as Sine.html. However, as noted on https://github.com/openzim/mwoffliner/issues/164 , the TeX/LaTeX representation of the equation is not present in the alt-text of the equation images in *this* ZIM, which is problematic for a maths-focused ZIM, and hopefully will be corrected in mwoffliner.

![image](https://user-images.githubusercontent.com/4304337/33701831-93373d0c-db18-11e7-969d-a9f5fa6af61a.png)

**Comment by kelson42** [comment] 2017-12-08 11:51
I appreciate to read that there is a workaround to that bug on kiwix-js-windows... but IMO the fundamental problem should be investigated and solved (here in kiwix-js).

**Comment by Jaifroid** [comment] 2017-12-09 12:46
@Sharun-s investigated this problem pretty fully, and we did a lot of testing on it. The conclusion was that until we can re-compile xzdec or find a replacement technology for it, the solution is to control the rate at which SVGs are queued for decompression. Web workers can also help distribute the load.

The [preload stylesheets](https://github.com/kiwix/kiwix-js/tree/Preload-stylesheets) branch of this repo has a progressive image display routine incorporated into it in jQuery mode (not in Service Worker mode). It displays the above page correctly (other than the extraneous HTML bug due to incorrect stylesheet hrefs in the ZIM).

**Comment by mossroy** [comment] 2017-12-11 12:30
@kelson42 there are a few fixes and enhancements like this one that could be merged upstream (i.e in kiwix-js). We identified some of them in August 2017 with @sharun-s and @Jaifroid , on a framapad. But none of us could really take enough time to work on it.
It's usually worth it in terms of user experience, but is not trivial technically, makes the code more complicated, and only applies to the jQuery mode.
In this particular example, queuing and multi-threading decompression tasks probably have no sense in ServiceWorker or WebRequest modes. Because it would be handled by the browser engine itself.

**Comment by Popolechien** [comment] 2017-12-11 14:56
Ok, I guess it is the same issue as in mwoffliner but since the discussion is ongoing I'd like to mention that a gentleman just wrote saying that this StackExchange entry https://mathoverflow.net/questions/184211/consequences-of-zfcx-lty-rightarrow-2x-lt2y appeared like this to him on Kiwix : 

![25189588_1226926447409345_1819224227_o](https://user-images.githubusercontent.com/21675885/33837069-85ec4e78-de8b-11e7-99db-4a73183a97fb.png)

**Comment by Jaifroid** [comment] 2017-12-11 15:48
Confirmed that it looks the same in Kiwix JS Windows, but as it's a TeX string, it could be interpreted with MathJax. Looking at the original page, it looks like there are no fallback images, and that the page uses MathJax to display the equations anywhere in the site. You'll see the second line of the first answer on that page also uses a raw TeX string which gets interpreted to an equation on the site, but not in Kiwix.

Currently the MathJax support in Kiwix JS UWP relies on finding the TeX in the alt text of the fallback image, which is what Wikipedia uses. So we have to hope that the TeX string is semantically marked in some way in order to be able to recognize it. If it is, it can be interpreted, either in mw-offliner when scraping or in the client.

Having said that, even if it's in mw-offliner, the reason for having MathJax in Kiwix JS is to work around the terrible memory performance and crashing of the app's engine when extracting tons of SVG files in all three main browsers. MathJax saves *a lot* of CPU cycles and memory headaches and is lightening fast.

**Comment by Jaifroid** [comment] 2017-12-11 16:04
PS Just to be clear, I don't think it is the same issue as https://github.com/openzim/mwoffliner/issues/164, because the issue there is that the alt text is not being inserted into the fallback image tag. The issue here seems to be that there is no fallback image, just the raw TeX, so we will need to interpret it with MathJax or similar at some point in the chain (but keep the alt-text TeX string if it's done in mwoffliner).

**Comment by Jaifroid** [comment] 2018-02-18 11:58
So I've now added (experimental) support for in-line TeX equations in https://github.com/kiwix/kiwix-js-windows/commit/267e575ba89ab8422a5180f7da447827c1d4b571 (in Kiwix JS Windows). It finds all $...$ and $$...$$ strings and converts them to dummy images with the TeX in the alt field of the image. Kiwix JS Windows then processes these images as if they were math fallback images from Wikipedia, rendering the TeX using MathJax. See screenshots below of page referenced above and another sample with a thicket of equations.

Two issues:

1. Potential for false positives, since $...$ strings can be quite common over several lines in different types of ZIM. The regex attempts to avoid matching strings where the second $ is not followed by a space or punctuation marks. However, it turns out some Mathoverflow TeX strings are not separated by spaces or punctuation, so those are not currently rendered. The search can be made more complete, but in that case the rendering would have to be limited by ZIM type.

2. Occasionally on reloading the same page previously viewed the equations get shifted down by one line while the text of the page remains a line higher, causing the page to become illegible. I am investigating the cause of this. It's odd, as it never affects the first page rendered.

I'm adding a separate message to this issue with my thoughts on backporting to Kiwix JS.

![image](https://user-images.githubusercontent.com/4304337/36351423-6ace4834-14a1-11e8-8b51-6f689227b920.png)

![image](https://user-images.githubusercontent.com/4304337/36351394-0f83136a-14a1-11e8-8b7a-6796e6028975.png)

**Comment by Jaifroid** [comment] 2018-02-18 12:13
I've added my thoughts on backporting such a solution to Kiwix JS in #297.

**Comment by kelson42** [comment] 2018-02-18 16:31
@Jaifroid I'm a bit lost in all of this honestly. So please forgive me if I write silly stuff.

MWoffliner can exports equations in different formats:
* Traditionally it was in PNG, but that is not really a good approach - even if there is no rendering issue with that
* Currently, at least for Wikipedia stuff, it exports in SVG, which is better... but not the best (we have this bug with the alt/title) and it is still "a picture". 
* Ultimate solution is MathJax, I'm not sure exactly if Mediawiki has the full support, but it is definitly the way we (will) go through.

BTW, I'm not a big supported of hacks trying to render things based on HTML attributes like "alt" or "title"... So far I know, this is not their purpose. Sorry if I have already written that somewhere.

SE files use MathJax AFAIL, so does that mean that kiwix-js-windows now fully support MathJax?

**Comment by Jaifroid** [comment] 2018-02-18 20:43
@kelson42  Kiwix JS Windows currently supports MathJax rendering in Wikipedia **if** the fallback image has the class `mwe-math-fallback-image`, and **if** there is an alt text containing the original TeX string. In that case, it renders the MathJax instead of the SVG and this works very well.

However, there is currently a bug in mw-offliner (https://github.com/openzim/mwoffliner/issues/164) which is leaving the alt-text blank in all of the new ZIMs that have been made, so forcing Kiwix-JS-Windows to use the SVGs instead (this bug is particularly problematic for `wikipedia_en_maths_novid_2018-01.zim`).

MathJax rendering is very quick and light in memory usage, whereas SVGs are very heavy to decompress and are liable to crash the app (especially on mobile, but even on desktop).

Regarding Stackexchange ZIMs, I have just [pushed to master](https://github.com/kiwix/kiwix-js-windows/commit/267e575ba89ab8422a5180f7da447827c1d4b571) some experimental support for MathJax rendering of the equations (seen in the screenshots above): in this case there are *no* fallback SVGs in the ZIM, it's just raw TeX strings in the body of the HTML. MathJax is currently the **only** solution for rendering such equations in Stackexchange ZIMs. The support is currently in testing (not yet pushed to the Store).

**Comment by kelson42** [comment] 2018-02-24 17:26
@Jaifroid Thank you for the clarification.

**Comment by Jaifroid** [comment] 2018-06-04 23:09
A commit https://github.com/kiwix/kiwix-js/commit/a9678828ece3015aaa744104716acb663b92cc6a now addresses this issue experimentally in regard to extracting SVGs.

[I still think MathJax is the more elegant solution, and despite this commit using WASM decoding, MathJax still renders equations faster. Hopefully we'll get TeX strings back in the newer ZIMs soon...]

**Comment by Jaifroid** [comment] 2020-03-04 08:52
I think this issue can be closed. We long ago fixed the crash caused by attempting to decompress too many SVG equations at once, and MathML equations now work in Service Worker mode for Stackexchange ZIMs (which do not have SVGs). In jQuery mode, equations don't work in Stackexchange ZIMs, but we throw up a banner asking users, if possible, to switch to Service Worker. Finally, Kiwix JS Windows exists as an alternative that does support MathJax (actually KaTeX) in jQuery mode if clients are limited to that. So, I think we cover all the bases.

**Closed by Jaifroid** 2020-03-04 08:52 UTC
Labels: bug

**Comment by kelson42** [comment] 2020-03-04 08:54
@Jaifroid Sounds good.
