### ISSUE TITLE
ZIM files not containing home button

### ISSUE THREAD

**Issue by wsteven-son** [kiwix/kiwix-js#690] opened 2020-12-17 00:00 UTC
Several ZIM files do not contain a home button, (Usually next to the dice) making the user have to refresh the original address in order to return to home when a back button isn't easy. Is this intentional? Seems the banner should be consistent across all ZIMs. I've listed some examples of ZIMs without home buttons. Thank you!

Wikisource
PhET Interactive
OpenStreetWiki
Computer by Wikipedia
Ted Talks- business

**Comment by kelson42** [comment] 2020-12-17 08:28
@wsteven-son None of our ZIM have an HOME button. The HOME button belongs the Kiwix (JS) user interface. It is always here and visible in the top left corner of your browser tab (I have tested with latest Phets ZIM file).

**Comment by Jaifroid** [comment] 2020-12-17 08:40
@wsteven-son Could you be more specific about which Home button you are expecting to see, and whether you are using Kiwix JS or another ZIM reader? If you are using Kiwix JS, please confirm if you are accessing files using Service Worker mode (see Configuration)?

**Comment by kelson42** [comment] 2021-01-10 17:07
Without feedback here, I would propose to close this ticket as INVALID.

**Comment by Jaifroid** [comment] 2021-01-11 00:31
@wsteven-son I'm closing this due to lack of feedback, but please re-open if you can explain further what the issue is.

**Closed by Jaifroid** 2021-01-11 00:31 UTC
Labels: invalid, question
