### ISSUE TITLE
The Travis build is unstable with Firefox 45

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#536] opened 2019-07-14 15:35 UTC
UI tests sometimes fail with :

> Timed out while waiting for element <#articleList> to be visible for 20000 milliseconds.

**Comment by mossroy** [comment] 2019-08-28 18:02
What I can see in Saucelabs (for example on https://app.saucelabs.com/tests/4d28dbb03b6b4d80acbd62b11bb70b23) is that, after typing "Ray" in the search field, the browser immediately displays the results, before we click on the search button.
For some reason, it makes the result list disappear, so it fails to find the article.
Maybe we should modify the script (or kiwix-js) to avoid this race-condition.

**Comment by Jaifroid** [comment] 2019-08-29 08:08
It is by design that results show without clicking the search button. However, clicking search should not then hide the results. It could be since we introduced the code to hide results if the search field loses focus. We could probably fix this by adding code to check that the focus is not the search button (if my hunch here is correct).

**Comment by Jaifroid** [comment] 2019-08-29 08:15
I confirm that clicking the search button after typing "ray" causes the results to disappear briefly before being shown again. Moreover, if we do search by clicking the search button, it is no longer possible to dismiss the results by clicking elsewhere in the app, because the onlostfocus event of the search button does not have a listener attached to it. It seems we need to add code to deal with this situation, as it does come across as a little buggy (even if it's a minor detail most users will never encounter).

**Comment by Jaifroid** [comment] 2019-09-01 16:31
Since commit https://github.com/kiwix/kiwix-js/commit/b954b323b2f8ea77abf5839dd604cc3f47056b66 this issue is no longer occurring. So I'm closing for now (but we can re-open if the issue re-occurs).

**Closed by Jaifroid** 2019-09-01 16:31 UTC
