### ISSUE TITLE
Broken display when search results have special characters

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#575] opened 2019-11-13 17:36 UTC
Example below (on stackoverflow_eng_all_2017-05.zim, after typing "Why should")
![image](https://user-images.githubusercontent.com/890923/68788631-12224500-0644-11ea-80cc-3b0cc3bfd534.png)
In this example, the issue certainly comes from the < and > characters, that are interpreted as HTML.

We should probably apply some HTML encoding before doing some string concatenation

**Comment by Jaifroid** [comment] 2019-11-13 18:04
Ouch, that looks a bit nasty!

**Comment by ayushiitr2901** [comment] 2019-12-02 11:16
Hi, I am new contributing to Kiwix and this issue seems to be great headstart. Can you please help me with how I can start with it, I would like to solve this issue.

**Comment by Jaifroid** [comment] 2019-12-02 11:23
@ayushiitr2901 Thank you for offering to contribute!
First you will need to be able to reproduce the problem, which may need you to download the latest version of the Stackoverflow ZIM.
Once you are able to reproduce it, start debugging with
`function populateListOfArticles(dirEntryArray)`
in `app.js`.
Once you have tested a solution in your own clone of this repo, you can make a Pull Request, and one of us will take a look at your code.

**Comment by vasusharma7** [comment] 2019-12-02 11:46
Sir
I was also interested in solving the issue and I looked for the zim files of stackoverflow and even downloaded a few.But I was not a able to find the exact zim file with the issue.....
If it doesnt bother you, Can you please send me the name or the link of the exact file as some of the files are very large in size and downloading all of them may not be feasible....

With reagrds
Vasu Sharma

________________________________

**Comment by mossroy** [comment] 2019-12-02 21:07
@vasusharma7 : I found another case in a (very) smaller zim file.
If you download https://download.kiwix.org/zim/stack_exchange/matheducators.stackexchange.com_en_all_2019-02.zim (81MB) and type "imp" in the search field, you'll see a broken search result on `Importance of "Calculus->Analysis Transition Books"?` : 
![image](https://user-images.githubusercontent.com/890923/69994833-0cd35e80-154f-11ea-91cb-6c6d17918a79.png)

**Comment by vasusharma7** [comment] 2019-12-02 21:12
Thanks a lot sir for quick help...It would really help me in solving the issue...

________________________________

**Comment by kelson42** [comment] 2019-12-08 13:00
It think this has been fixed by #578

**Closed by kelson42** 2019-12-08 13:00 UTC
Labels: bug, good first issue
