### ISSUE TITLE
Deal correctly with article titles containing a forward slash

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#494] opened 2019-05-08 20:19 UTC
Currently, on master, `parseAnchorsJQuery` gets confused by titles such as `A/Singapore/Riverside`. It thinks that it is dealing with a subdirectory, when in fact it is dealing with a title `Singapore/Riverside`. Hyperlinks on that page therefore do not work, as the base html tag is incorrectly set (I believe). We perhaps are not percent-encoding the title at the right point (or maybe we percent-decode it too early).

**Comment by Jaifroid** [comment] 2019-05-08 20:35
The problem seems to be here (lines 889-891 of `app.js` in master):
```
// Compute base URL
var urlPath = regexpPath.test(dirEntry.url) ? urlPath = dirEntry.url.match(regexpPath)[1] : '';
var baseUrl = dirEntry.namespace + '/' + urlPath;
```
Examining `dirEntry.url` it contains `Singapore/Riverside`. I guess we will have to substract the title from the url and test the stub instead? Any other thoughts on how to deal with this, @mossroy ?

**Comment by Jaifroid** [comment] 2019-05-08 20:43
NB I forgot to say I was seeing this in `wikivoyage_en_all_novid_2019-04.zim`. Interestingly, in `wikivoyage_en_all_novid_2019-03.zim`, I'm seeing the `dirEntry.url` for the same page presented as `Singapore_Riverside.html`, which looks much more sensible. Is `Singapore/Riverside` an illegal value for a `dirEntry.url`?

**Comment by Jaifroid** [comment] 2019-05-08 20:53
@kelson42 , could you have a look at this thread? I suspect it may be an issue in mwoffliner, not Kiwix JS. 

To summarize, the issue is that `dirEntry.url` for the article "Singapore/Riverside" is `Singapore_Riverside.html` in wikivoyage_en_all_novid_2019-03.zim, whereas it is `Singapore/Riverside` in wikivoyage_en_all_novid_2019-04.zim,.

While the latter is not an illegal URL, it is I think an illegal filename, because it looks like it is an article `Riverside` inside a directory `Singapore`. If you agree this is a problem, I can open an issue on mwoffliner.

**Comment by kelson42** [comment] 2019-05-09 04:35
@Jaifroid The concept of directory (and sub-directory) does not exist in ZIM specs. We have on-purpose made an effort on MWoffliner to keep Wikipedia URL schema in the ZIM file. It should be always the same now, and this is the case here. So this is a feature, not a bug.

**Comment by kelson42** [comment] 2019-05-09 05:15
@Jaifroid What I need to add, is that of course the relative links within the HTML page of this article should take that in account an have an additional `../`

**Comment by Jaifroid** [comment] 2019-05-09 06:17
Thank you, @kelson42 , that's helpful. We introduced "subdirectory" support due to Stackexchange ZIMs, but it's encountering a problem here due to the change in URL format. Indeed the address of the page on Wikipedia is `https://en.wikivoyage.org/wiki/Singapore/Riverside`.

@mossroy It looks like we need to work around this issue in jQuery mode. In SW mode it works.

**Comment by kelson42** [comment] 2019-05-09 06:21
@Jaifroid I think you talk of URL like this one http://library.kiwix.org/stackoverflow.com_en_all_2019-02/A/question/2003505.html ? Please tell me if this kind of URL is fundamentally different from "Singapore/Riverside"... because it should not IMO.

**Comment by Jaifroid** [comment] 2019-05-09 08:42
@kelson42 , there should be no fundamental difference, though there is something weird going on, and I think it's to do with the page's ZIM URL being referenced in some places as `A/Singapore/Riverside` and in others as `A/Singapore%2FRiverside`. Clearly that's going to make a big difference to how the browser interprets relative links. I'll investigate further.

**Comment by Jaifroid** [comment] 2019-05-09 08:57
@mossroy I'm trying to get my head around what's happening here. There seems to be an inconsistency between how the assets are referenced  and how hyperlinks are referenced on the page `Singapore/Riverside`. In the raw HTML from the ZIM, the stylesheet `src`s are referenced with an extra `../`, like this:
```
<link href="../../-/s/css_modules/ext.kartographer.link.css" rel="stylesheet" type="text/css">
```
But hyperlinks are missing the extra `../`, and look like this:
```
<a title="Singapore" href="Singapore">Singapore</a>
```
In our jQuery mode, the stylesheets are correctly found, but the hyperlinked article cannot be found. When clicking on the above hyperlink, we get the error "Article with title A/Singapore/Singapore not found in the archive".

In SW mode it all works, and I think it's because the iframe is set to `A/Singapore%2FRiverside` (note the percent-encoding of the forward slash). But then I don't understand why the assets are found...

**Comment by kelson42** [comment] 2019-05-10 07:54
> M URL being referenced in some places as `A/Singapore/Riverside` and in others as `A/Singapore%2FRiverside`. Clearly that's going to make a big difference to how the browser interprets relative links. I'll investigate further.

@Jaifroid Indeed. We have here two ways of writing this URL. But I'm quite sure that both should open the same article in the ZIM and I don't think this should change anything in the HTML of the article.

See this test with the online article:

```
$ wget "https://en.wikivoyage.org/wiki/Singapore%2FRiverside" -O 1.html
--2019-05-10 09:53:28--  https://en.wikivoyage.org/wiki/Singapore%2FRiverside
Resolving en.wikivoyage.org (en.wikivoyage.org)... 2620:0:862:ed1a::1, 91.198.174.192
Connecting to en.wikivoyage.org (en.wikivoyage.org)|2620:0:862:ed1a::1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 262874 (257K) [text/html]
Saving to: ‘1.html’

1.html                                             100%[================================================================================================================>] 256.71K  --.-KB/s    in 0.08s   

2019-05-10 09:53:28 (3.27 MB/s) - ‘1.html’ saved [262874/262874]

$ wget "https://en.wikivoyage.org/wiki/Singapore/Riverside" -O 2.html
--2019-05-10 09:53:34--  https://en.wikivoyage.org/wiki/Singapore/Riverside
Resolving en.wikivoyage.org (en.wikivoyage.org)... 2620:0:862:ed1a::1, 91.198.174.192
Connecting to en.wikivoyage.org (en.wikivoyage.org)|2620:0:862:ed1a::1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 262874 (257K) [text/html]
Saving to: ‘2.html’

2.html                                             100%[================================================================================================================>] 256.71K  --.-KB/s    in 0.08s   

2019-05-10 09:53:35 (3.25 MB/s) - ‘2.html’ saved [262874/262874]

$ diff 1.html 2.html 
```

**Comment by Jaifroid** [comment] 2019-05-10 08:06
@kelson42 Thanks for that test! In Kiwix JS in jQuery mode, we have a regex (or two) that parses the URL and we then use JS to set the destination of the hyperlinks in the article (to extract them from the ZIM), so we have to adjust our regexes. We also have to set a baseUrl in the HTML so that relative URLs are handled correctly.

Thanks for opening https://github.com/openzim/mwoffliner/issues/726 as a separate issue. I'm now suspecting that that is the real problem here, as it does look like the assets and the hyperlinks have inconsistent relative links, but I await the opinion of others.

**Comment by kelson42** [comment] 2019-05-10 08:11
@Jaifroid Good :) I strongly suspect that if you have to introduce a `<base>` node in an article HTML coming from the ZIM, then something is fundamentally wrong. You should not have to do so. We have decided years ago to make only relative URLs in the  ZIM files articles to avoid to do this in multiple occasions. Please consider this carefully.

**Comment by Jaifroid** [comment] 2019-05-10 08:21
I meant that we already have a `<base>` tag introduced in the code in jQuery mode (not in Service Worker mode). This was coded by @mossroy to support Stackexchange ZIMs: https://github.com/kiwix/kiwix-js/pull/310. It does work very well and seems robust. Let's see what happens with https://github.com/openzim/mwoffliner/issues/726 .

**Comment by Jaifroid** [comment] 2019-05-15 21:23
@mossroy This issue has been fixed in mwoffliner. However, the fix will expose a problem in the way we currently set the iframe URL for the Service Worker The problem is [this line](https://github.com/kiwix/kiwix-js/blob/9cc7cb9ff04576e33cd69420856c1afb6af7a472/www/js/app.js#L776):
```
iframeArticleContent.src = dirEntry.namespace + "/" + encodeURIComponent(dirEntry.url);
```
This sets the source of the iframe to the encoded form of the URL, but `encodeURIComponent` encodes forward slashes, so a url like `A/Singapore/Riverside` will be set as `A/Singapore%2FRiverside`. While the file will be read correctly by the borwser, the `%2F` causes the SW to think it's in the wrong directory as far as any relative asset links on the page are concerned.

The reason we use `encodeURIComponent` at this point is to solve another problem, as per [discussion here](https://github.com/kiwix/kiwix-js/issues/428#issuecomment-429742993). It was a rather specialized issue.

In sum, we will need to monitor this and be aware, as new ZIM types come through. The issue has not been exposed till now because previously we would never have had a ZIM URL like `A/Singapore/Riverside`. Instead, it was `A/Singapore_Riverside.html`.

**Comment by Jaifroid** [comment] 2019-05-15 21:41
@mossroy This issue can currently be reproduced in Stackexchange ZIMs. Steps to reproduce:

1. Load any Stackexchange ZIM with subdirectories in Service Worker mode;
2. Navigate to a page in a subdirectory and note the page's title (you will need to search for this page in step 4);
3. Click on a link, it will work (because page has been loaded natively by the browser).
4. Now use the UI search to search for the page in step 2;
5. Click on the same link you clicked on earlier. It will fail.

Reason it fails is because you have loaded the page via app.js, not natively in the SW, and app.js has the above line which encodes the URL. 

Here is an example of a URL in a Stackexchange article loaded natively in SW: `http://localhost/Repos/kiwix-js/A/tag/uso-de-palabras/1.html`.

Here is an example of the same URL in the page that has been loaded into SW by app.js:
`http://localhost/Repos/kiwix-js/www/tag/uso-de-palabras/1.html`

**Note the extra (incorrect) `www` in the path in the second case.** This is proof of the issue.

**Comment by mossroy** [comment] 2019-06-01 09:19
I'm confused about this issue.
If I try to sum up, there was an initial problem with forward slashes in jQuery mode, that has been fixed in mwoffliner, but for which we should run more tests, when a new version of wikivoyage_en will be available (the last one in https://download.kiwix.org/zim/wikivoyage is still wikivoyage_en_all_novid_2019-04.zim, which does not have the fix).

And there is what seems like a different problem in SW mode. I did not manage to reproduce it with Chromium 73 or Firefox 67 and askubuntu.com_en_all_2019-01.zim. Should I test with a specific ZIM file?

If these problems are indeed different, could you please separate them in 2 github issues, so that we can track them individually?

**Comment by Jaifroid** [comment] 2019-06-01 10:01
@mossroy You're right, that as I investigated this issue, and got the central problem with the ZIM file format fixed, it morphed into a different issue. #498 addresses a related but different issue which arose while investigating the original issue. I'll open a new issue, but I think this one should remain open until we are able to test ZIM files produced by the fix in mwoffliner.

**Closed** 2019-07-20 11:24 UTC
Labels: bug
