### ISSUE TITLE
Ubuntu touch support

### ISSUE THREAD

**Issue by ernesst** [kiwix/kiwix-js#285] opened 2017-07-16 04:39 UTC
Gents, 

For information, i've packaged, without modification, kiwix-js for Ubuntu touch, a mobile OS supported by Ubports.com
See the link : https://open.uappexplorer.com/app/kiwix

Please let me know if you have any remarks
Regards

**Comment by kelson42** [comment] 2017-07-16 07:00
@ernesst That sounds great, even if I can not test it as I do not have an Ubuntu mobile phone. Are you interested to maintain it over time?

**Comment by Jaifroid** [comment] 2017-07-16 07:27
Great to see this! Likewise I can't test. It's cool that kiwix-js is enabling support on so many platforms. I'll leave the policy issues to @kelson42 , but you've done what we're about to do for the Windows Store in a few weeks and are aiming to publish it as an official Kiwix package -- see https://github.com/kiwix/kiwix-js-windows . The Ubuntu store page looks good!

**Comment by mossroy** [comment] 2017-07-16 12:00
Excellent!
Very glad to see this code can be used on other platforms/devices.
What is the browser engine (and version) used by the webview of ubuntu touch?

**Comment by ernesst** [comment] 2017-07-16 16:00
Hello, 

The app works nicely on my phone. Thanks for the support offer however i don't know how to code :) just learn recently how to pack for ubuntu phone, so i'm looking for great project in github. 

Can you confirm the normal feature that each start, the app return in configure mode and the zim package has to be load again ? 

I've to look for the browser engine.

**Comment by Jaifroid** [comment] 2017-07-17 06:41
@ernesst Unfortunately yes, this is the current behaviour on startup due to security policy in browser engines. #287 (Use Cordova) could help, but has not been developed yet. The return from configure mode should *not* require reload of the ZIM, but it does require searching and reloading the article. There is, I believe, scope for changing this behaviour if the user hasn't changed a setting that requires reloading the article. We should create an issue for this.

**Comment by mossroy** [comment] 2017-07-17 11:51
@ernesst : I think @kelson42 does not ask you to code. He's asking if you would be willing to maintain the Ubuntu Touch package. IMHO, it would involve testing new versions of kiwix-js on Ubuntu Touch from time to time, and update the package when a new release of kiwix-js is done.
@Jaifroid : the issue you mention already exist (it's an old one) : #127

**Comment by ernesst** [comment] 2017-07-17 22:26
Ok thanksm i wanted to ensure that the behavior isn't due to the operating system.

Sure i can maintain the Ubuntu Touch package and keep it up to date on the store. How can i know if a new release is done ?

**Comment by Jaifroid** [comment] 2017-07-18 02:03
@ernesst , If you pop in from time to time, we'll let you know! I really want to get a UWP version 1.0, or possibly 0.9 Beta into the Windows Store by mid August, for example, and the current milestone for kiwix-js version 2.2 is 31st October.

**Comment by kelson42** [comment] 2017-07-18 06:32
@ernesst Nice! Would be great to have the bit of packaging stuff (documentation, scripts) here in a dedicated repo on which I could put you admin. Then to share the account of uappexplorer.com with one of us. Then we could integrate it properly to the Kiwix project portfolio. Would that be acceptable to you?

**Comment by mossroy** [comment] 2017-07-18 11:50
@ernesst The release dates of future versions are subject to lots of changes. If you're not around, we can ping you (by mentioning you in a comment, for example) when a new version is about to be released.
In any case, I'm very interested to have more technical info on the browser engine that is used in your WebView of Ubuntu Touch. In particular to know if it supports some recent technologies like Service Workers, Web Assembly etc
It would also be better to follow the same version numbers for every platform, and to use a released version instead of the latest from git.

**Comment by ernesst** [comment] 2017-07-19 02:27
@kelson42 the modification are really small to package it, it basically needs just some extra information like package maintainer name, email etc + renaming the app according to ubuntu touch policy. 
I'll look how to create my repo and upload my small work. 
However, for info it's base on : https://github.com/iambumblehead/ubports-little-webapp
I've modified  the /package.json of kiwix-js and create the 3 files + icons in the platform/click. 
Then use makeclick.sh. 
I guess all the file can be easily integrated in your project.

Regarding openstore / uappexplorer.com account it's really easy to create one, so we can create one for kiwix app only and share it. 

@mossroy 
What i've found the browser should be oxide browser which uses chromium 54. 
For detail, the code is here : https://github.com/ubports/webbrowser-component

If you can give me a specific version with it number I can repack, please do.

**Comment by Jaifroid** [comment] 2017-07-19 08:56
@ernesst , see #127 for implementation of a link for returning from the Config tab to the Home tab without reloading the page. Best to wait until / if it is added to the main branch, as there may be modifications first (it is under review as PR #291 ).

**Comment by mossroy** [comment] 2017-07-19 19:50
@ernesst : thanks for the info.
Regarding the browser engine, where did you get this info?
When I search for oxide in the https://github.com/ubports/webbrowser-component repo, I see various versions imported : 1.0, 1.7, 1.8, 1.15, 1.19 etc. How can I know which one is used in the WebView?
I suppose the Chromium version used by Oxide can be found in its commit log : https://git.launchpad.net/oxide/log/
In any case, it probably means we can't use WebAssembly (needs Chromium>=57, which means Oxide >=1.21), but we might use ServiceWorkers (needs Chromium>=45, which means Oxide>=1.9)

**Comment by mossroy** [comment] 2017-07-25 20:31
@ernesst : if the additions needed to create a package for ubuntu touch are that simple, we might think about putting them directly in this kiwix-js repo. This would allow to integrate it with our continuous integration (which creates nightly builds, automates the generation of packages of released versions etc).
But we need to see what it is precisely before : could you share these files with us?

**Comment by ernesst** [comment] 2017-07-25 23:37
@mossroy, sorry for the delay, how can i share the files with you ?

**Comment by mossroy** [comment] 2017-07-26 14:45
@ernesst : I've tried to package the .click file with our continuous integration on Travis. See branch add-ubuntu-touch-click-packaging 
Could you test the .click package that has been generated in http://download.kiwix.org/nightly/2017-07-26/ ?

I only had a few difficulties to do it : 
- I could not merge the manifest.json with the existing one, because the click command-line does not like the extra properties, so I had to keep a separate one for Ubuntu touch
- I had to remove the .woff and .woff2 files of bootstrap because the click command-line refused to create a package with those files (considered as binaries in a package for all architectures)
- I had to switch to trusty distribution on Travis, in order to be able to have the click command-line available in the repository
- This click command-line is probably an older version than the one available on xenial, and it does not seem to support the --ignore option

**Comment by ernesst** [comment] 2017-07-26 15:20
1) yes possible, the policy on Ubuntu touch is very strict, now that ubports got the project it should be a bit unleash in the future
2) Yes correct i forgot to mention that
4) I think it's the same for me on xenial.

I've tested the click, it works well, congrat !
There is still my mail attached to the package, shouldn't be better to set kiwix support email ?

**Comment by ernesst** [comment] 2017-07-26 15:39
I guess now Kiwix can officially create an account https://openstore.ubports.com/, then i'll retired my package.

**Comment by mossroy** [comment] 2017-07-26 18:48
That's good news!
I'll create a Pull Request with those changes, so that .click files will be automatically generated with nightly builds, and also on tags (for releases).
Regarding the "maintainer" property in ubuntu_touch/manifest.json, that depends on what it means, and how it's used by Ubuntu.
You're the one who initially created the package, the one who can test future versions and who knows the platform. This seems close to what a "package maintainer" is (with the same meaning as for Debian packages for example).
But I agree with you that you're not the "code/application maintainer".
I don't mind putting a generic kiwix contact email everywhere at all, but it was a way to give you the credit for the port. What would your prefer?

@kelson42 : regarding the kiwix store account, there are 2 choices :
- create a new ubuntu account for kiwix
- create a new (or use an existing) github account for kiwix, that can be used with Single Sign On, I suppose
See https://openstore.ubports.com/login
I suppose I should create an ubuntu account?

@ernesst what do you mean by "retiring" your package? Isn't there a way to "transfer" the ownership of an app to another account?
Because if you remove your package, I suppose the people already using it will not get the upgrades we will upload afterwards?

**Comment by kelson42** [comment] 2017-07-26 19:04
@mossroy @ernesst For emails, please give contact+ubuntutouch@kiwix.org (or replace "ubuntutouch" by something better) for any offlicial Kiwix release. Any important bug report or question will be then forwarded somehow to the developers.

**Comment by mossroy** [comment] 2017-08-02 12:58
@ernesst  I've created a "kiwix-offline" ubuntu account that allows to login on the store.
It looks like I should be able to submit a .click package with it.
Ideally, the .click package you already submitted would be transferred to this account (is it technically possible?), and we would update it on each release of kiwix-js after some tests. This way, I suppose the users that downloaded your package would get the updates automatically.
Could you tell us if it's possible?

**Comment by ernesst** [comment] 2017-08-02 13:36
I've made a request to the store owner to see the feasibility to transfer package ownership.

**Comment by ernesst** [comment] 2017-08-02 14:51
Hello can you give me the email for the ubuntu store account ? the transfert of ownership is possible.

**Comment by mossroy** [comment] 2017-08-02 16:33
The email of the ubuntu account is contact@kiwix.org, login kiwix-offline

**Comment by ernesst** [comment] 2017-08-02 20:23
Done, you should have the ownership now

**Comment by mossroy** [comment] 2017-08-02 20:58
@ernesst : cool, it worked!

**Comment by mossroy** [comment] 2017-08-02 21:07
@ernesst : could you have a look at the Pull Request #295 : if it's OK for you I would merge it, so that we have nightly builds for Ubuntu Touch.
It would allow me to upload a nightly build to the store, so that you might check if it's properly upgraded on your device.
Afterwards, we would only upload released versions in the store, starting with version 2.2

**Comment by mossroy** [comment] 2017-08-06 18:22
OK, We now have nightly builds for Ubuntu Touch : http://download.kiwix.org/nightly/
Can I try to upload the latest nightly on the store?

**Comment by ernesst** [comment] 2017-08-06 20:08
Sure why not as soon done let me know i'll confirm that everything is fine.

**Comment by mossroy** [comment] 2017-08-06 21:17
The .woff and .woff2 are back in the latest nightly package, so it's rejected by the store.
I had made a mistake in the script, I'm fixing it.

**Comment by mossroy** [comment] 2017-08-07 19:17
@ernesst : I've fixed the issue on .woff* files, and uploaded the nightly version to the store.
Could you please check that you get the upgrade from the store on your device, and that it's still working?

**Comment by ernesst** [comment] 2017-08-08 02:11
I've downloaded the latest version, no problem to use it/no bug. 
Thanks

**Comment by mossroy** [comment] 2017-08-08 17:53
That's cool!
So I'll close this issue.

I'll try to ping you from time to time to test some nightlies (if we're close to create a new release, or if we introduced significant code changes).

Again, thanks a lot for this contribution.

**Closed by mossroy** 2017-08-08 17:53 UTC
Labels: question

**Comment by mossroy** [comment] 2018-01-02 18:33
@ernesst : we'll probably release a 2.2 version of kiwix-js soon.
Could you please test the latest nightly (from https://download.kiwix.org/nightly/) on ubuntu touch, to check there has been no regression on your device?

**Comment by ernesst** [comment] 2018-01-03 12:45
Thanks, it seems working fine. 
Where can i find the changelog ?

**Comment by mossroy** [comment] 2018-01-03 17:28
I've created a PR to add the changelog of v2.2 in #327 , which should be merged soon.
It would be worth testing some stackexchange ZIM files, for example

**Comment by ernesst** [comment] 2018-01-07 01:07
Ok, thanks i tried the version 2.2commit-f962cd4 no problem noticed. Thanks
