### ISSUE TITLE
Add a "print" feature

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#888] opened 2022-09-10 17:30 UTC
If you just use ctrl-p in your browser, it will (badly) print the UI and only the beginning of the content (see #887)
It works well if you ask the browser to print the content of the iframe. On Firefox, you can right-click in the content, choose "this frame" -> "print the frame".

To avoid this issue, I don't see a better solution than to provide a "print" feature in the app, that would trigger the browser print on the iframe:

`document.getElementById("articleContent").contentWindow.print()`

**Comment by BBentleyDev** [comment] 2022-09-11 16:49
Hi there, can I be assigned this issue?

**Comment by Jaifroid** [comment] 2022-09-11 21:28
This issue is a duplicate of #350. That issue has some more information. A feature implementing this was developed for Kiwix JS Windows, and can be tested by going to https://pwa.kiwix.org.

**Comment by Jaifroid** [comment] 2022-09-11 21:35
I transferred comment above to #350.

**Closed by Jaifroid** 2022-09-11 21:35 UTC
Labels: duplicate, enhancement, good first issue

**Comment by mossroy** [comment] 2022-09-12 08:27
Thanks @Jaifroid , I had indeed forgotten this existing ticket
