### ISSUE TITLE
Code cleanup for Tab transition animation

### ISSUE THREAD

**Issue by RG7279805** [kiwix/kiwix-js#1101] opened 2023-09-07 09:26 UTC
While working on issue #846 Adding a new tab seems more complex than expected code seems really confusing and there is a lot of repetition for the same function
check out 
 https://github.com/kiwix/kiwix-js/blob/main/www/js/lib/uiUtil.js#L490

**Comment by Jaifroid** [comment] 2023-09-07 15:12
Thanks! This is probably a duplicate of #78? Or at least, it might also close #78.

**Comment by Jaifroid** [comment] 2023-09-07 17:14
Also see #701.

**Comment by Jaifroid** [comment] 2023-09-09 10:02
Closing as duplicate. Please add any discussion in #78.

**Closed by Jaifroid** 2023-09-09 10:02 UTC
Labels: duplicate, cleanup, remove-jquery

**Comment by Jaifroid** [comment] 2023-09-09 10:03
Or add discussion to #701 if more appropriate.
