### ISSUE TITLE
Release 3.3.0

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js#802] opened 2022-01-15 11:14 UTC
The 3.3 milestone is already quite interesting and has still a lot of work to do. I see work to do for at least 4 months. Last release is already almost 6 months ago. Release early, release often is good. I want to encourage you to reassess the milestone to 3.3.0.

- [x] Merge at least #792, #797, #800
- [x] Fix critical bug #806
- [ ] ~~Possibly merge #804~~
- [x] Update the changelog file
- [x] Further tests 
- [x] Rename existing milestones (increment their names), create a new 3.4 milestone and move open issues to this new 3.4
- [x] Create a tag on git
- [x] Generate unsigned extensions (should be automatically triggered on GitHub Actions by the tag creation)
- [x] Check that the PWA version is correctly set in moz-extension.kiwix.org (should be automatically triggered by tag creation) - had to do this manually
- [x] Upload the unsigned extensions to Stores:
  - [x] Firefox - https://addons.mozilla.org/fr/developers/addon/kiwix-offline/edit
  - [x] Chrome
  - [x] Edge - https://partner.microsoft.com/en-us/dashboard/microsoftedge/
  - [x] Ubuntu touch - https://open-store.io
- [x] Prepare the source code for version 3.4
- [x] When available, copy the signed extension binaries to https://download.kiwix.org/release/browsers/
- [x] Update the kiwix.github.io implementation - should no longer be required, but check that the implementation is synchronized automatically with master
- [ ] Publicize these new versions

**Comment by Jaifroid** [comment] 2022-01-15 12:31
@kelson42 - [I fixed tick boxes above]

I agree we are quite close. We don't need to do everything marked as v3.3, we can push those not complete and those that are not essential to v3.4. I'll add the current PRs we should merge to this.

**Comment by mossroy** [comment] 2022-01-15 18:20
I fixed the version numbers in the tick boxes.

I agree we're close to have enough changes to release a 3.3

**Comment by Jaifroid** [comment] 2022-01-20 20:48
See #805 for initial changelog.

**Comment by mossroy** [comment] 2022-02-02 10:48
I suggest that we try to do this release this week-end, if possible.
If the current open PRs are not merged, they will be for next release, never mind

**Comment by mossroy** [comment] 2022-02-04 13:24
I've done some tests on my Firefox OS device, with various ZIM files.
Apart from #814 , I did not find any issue.

**Comment by Jaifroid** [comment] 2022-02-05 11:22
@mossroy I've just updated the implementation at moz-extension.kiwix.org to be inline with current master. This will facilitate testing. I'd like to do a bit more testing of the switch between JQuery and SW in Firefox extension, as this is the headline feature of this release... I propose to complete these tests today, so we can create the tag tomorrow.

What should we do about the Ubuntu phone release? Cross fingers and hope? I'm not even sure ernesst is using that version any more!

**Comment by mossroy** [comment] 2022-02-05 11:46
Thanks.
Yes, I agree, I'm currently testing too.

Regarding Ubuntu phones, I think we can not do anything more than "cross fingers", until we have another tester.
But I think we should still release and deploy for this device. Unless they changed the underlying browser engine (which seemed to be a not-so-old Chromium), I think it's unlikely that a regression would happen on this platform, and we never heard of any regression so far.
In any case, there are 2 possibilities:

- new releases work well on Ubuntu phones, and their users are happy
- there are regressions and hopefully someone will report them here, and would become a tester

**Comment by cibersheep** [comment] 2022-02-05 13:47
> Regarding Ubuntu phones, [...]

Hello, just passing by :)
I can test for Ubuntu Touch. If you need more testers, the [forum of the community](https://forums.ubports.com/category/35/app-development) is a great place to announce

Now that I'm here, I cannot seem to find any click. Do you have a link or do I have to build  the project?

**Comment by Jaifroid** [comment] 2022-02-05 13:57
@cibersheep Thank you, amazing you saw this!

There's a click here: http://download.kiwix.org/nightly/2022-02-05/ . The only thing is that there was a merge this morning, so it might be good to test also after tonight's is generated. If you're able to test, that would be great.

**Comment by cibersheep** [comment] 2022-02-05 14:02
Ah! Awesome. Thanks. I can do that ;)

**Comment by cibersheep** [comment] 2022-02-05 14:30
I'm testing on Pixel 3a latest dev:
- Install click: ok
- API warning: ServiceWorker API available but not registered
- API error: Error loading ZSTD descompressor
- Load a zim file
- Search finds results
- Tapping on a result shows loading icon

log: https://dpaste.com/6HZUX2QED

**Comment by Jaifroid** [comment] 2022-02-05 14:35
@cibersheep Thank you. So you get the spinner but it never stops, and doesn't show an actual article?
For comparison, I wonder if you could check the same ZIM archive by visiting the test implementation here in the device's browser:

https://kiwix.github.io/kiwix-js/

**Comment by Jaifroid** [comment] 2022-02-05 14:44
So according to the log, the required decoder (ZSTD) is not loading, as we get `Could not instantiate any ZSTD decoder! TypeError: Failed to fetch file:///usr/share/morph-browser/ContentPickerDialog.qml:118: ReferenceError: acceptTypes is not defined`.

I haven't seen a need for `acceptTypes` before. Could this be a framework-specific error? Maybe a packaging error as we probably haven't updated the click packager with all the files or file types required? I'm guessing a bit here, though the log is very useful.

**Comment by mossroy** [comment] 2022-02-05 15:20
@cibersheep : great to have you here to test on Ubuntu Touch!
Could you install some older versions of kiwix-js, to see if they are better on your device/software? https://open-store.io/app/kiwix/versions

When we have more information, we should open a separate ticket for that.

**Comment by cibersheep** [comment] 2022-02-05 15:52
> @cibersheep Thank you. So you get the spinner but it never stops, and doesn't show an actual article? For comparison, I wonder if you could check the same ZIM archive by visiting the test implementation here in the device's browser:
> 
> https://kiwix.github.io/kiwix-js/

This was a lot faster! Nice.
- Loaded zim file
- It showed some articles
- Search worked as in the app
- Selecting an article showed it quite fast
log (Morph): https://dpaste.com/8J9WEX8SP


> So according to the log, the required decoder (ZSTD) is not loading, as we get `Could not instantiate any ZSTD decoder! TypeError: Failed to fetch file:///usr/share/morph-browser/ContentPickerDialog.qml:118: ReferenceError: acceptTypes is not defined`.
> 
> I haven't seen a need for `acceptTypes` before. Could this be a framework-specific error? Maybe a packaging error as we probably haven't updated the click packager with all the files or file types required? I'm guessing a bit here, though the log is very useful.

I think TypeError is an error for the toolkit. Nothing specific for Kiwix app

> EDIT: I'm not sure why the ContentPickerDialog is throwing an error, but as it seems you were able to pick the ZIM archive and even search it, then I assume that error is immaterial. 

Is a known error. It shouldn't prevent the Picker to load the file. As I'm able to search for articles, I assume they are loaded correctly (?)

> The more serious error is not loading the decoder. We have two decoders, XZ for older ZIM archives, and ZSTD for newer ones (last 18 months or so). We only instantiate the one needed for a specific ZIM archive. There is an XZ-encoded split ZIM in the `tests` directory. It would be very useful to find out if you can open and see articles from that ZIM. You need to pick ALL the parts in the file picker. This will tell us if the problem is specific to the ZSTD decoder or not.
> 
> Searching for results does not require the decoder, but accessing an article does.

When opening the app for second time:
- JS error is more useful[1]
- zim file is not present

[1] 
![imatge](https://user-images.githubusercontent.com/6640041/152648548-617953fa-34f1-4fd3-aee6-7a257a349ec7.png)



> @cibersheep : great to have you here to test on Ubuntu Touch! Could you install some older versions of kiwix-js, to see if they are better on your device/software? https://open-store.io/app/kiwix/versions
> 
> When we have more information, we should open a separate ticket for that.

Mmm v3.2.0 seems not to load the zim file at all. Decoder error is the same. I'll test older versions in a sec

**Comment by Jaifroid** [comment] 2022-02-05 16:29
@cibersheep Yes, the fact you can pick the ZIM and search for articles (and get a list of articles matching the search) shows that the file picker error is immaterial.

The issue is the way the decoder is failing to load. It's strange, because the decoder loads in IE11 when accessing from the file:// protocol, so it can't be an issue with the fact that the Ubuntu touch framework uses file://

The warning dialogue box above: this should actually disappear with tonight's nightly, because this morning's merge was precisely a fix for a bug that makes incompatible frameworks attempt to switch to Service Worker mode. The message shown is actually harmless, it's just telling you that the app tried (erroneously) to switch to using a Service Worker when that is not possible over the file:// protocol.

The fact that the test implementation works in the device's browser shows that there is no fundamental incompatibility in the code, which is good. It also means that it should be possible to use this app as an offline-first PWA if all else fails (and if Service Worker mode is supported when accessing the https:// implementation).

However, the main task is to find out why 3.1.0 works, when the later ones don't.

**Comment by Jaifroid** [comment] 2022-02-05 16:40
OK, it's undoubtedly this change in v3.2.0:

* NEW: Use fast binary WASM decoders with fallback to ASM if necessary

I think loading WASM is failing, and the fallback option is not being detected. I don't know exactly why. It works in Chromium extensions which also use the file:// protocol and a Chromium browser, so there is no obvious reason why it's failing here.

As a quick fix (monkey wrench.......) we could explicitly load the ASM versions (which are actually just as fast, btw) if we can detect that this will fail. I think we do something like that for IE11. But this should probably be a new issue. I'll see if I can move these comments.

**Comment by Jaifroid** [comment] 2022-02-05 16:48
I've opened #820, so we can continue discussion there.

**Comment by mossroy** [comment] 2022-02-05 17:07
Thanks @Jaifroid 
To come back to release 3.3.0, I've done a few tests (on master) in Firefox and Chromium extensions and did not see any issue (except the problems of inline scripts for Chromium extension when used in SW mode: #789 )
On Firefox, I managed to switch from/to PWA mode and it worked fine. But it's certainly worth more precise testing from you, @Jaifroid

**Comment by Jaifroid** [comment] 2022-02-05 17:15
OK, I've been testing. One nice thing is that when I loaded up the latest code as an unpacked extension in Firefox Developer edition, it went straight through to Service Worker mode (the last mode I had used with the extension some weeks ago), and the version loaded was clearly its old cached version (it didn't have the Reset button).

Because the version number has not changed, it didn't attempt to load new code from the server, even after a restart. **This is the intended behaviour, and shows that the browser has kept the cached version and that it is working offline a few weeks after I last attempted to access that extension.**  I *have* used this browser for other things in the meantime.

I think this counts as a longer-term test of offline capability of the PWA!

(I have now reset that version manually, so I can test the latest code from the server.)

**Comment by Jaifroid** [comment] 2022-02-05 17:25
@mossroy Assuming #820 isn't a blocker for v3.3, would we release the extensions and the PWA, but delay releasing the Ubuntu click package until we have a solution for #820? It looks quite low-level (may require recompiling decoders with latest Emscripten).

**Comment by mossroy** [comment] 2022-02-05 18:22
I agree. #820 should not be a blocker.
The 3.3.0 release will generate all packages, but we could avoid uploading the 3.3.0 click file, indeed.
3.2.0 was already broken on this device, but maybe uploading the 3.3.0 on open-store.io would annoy people who reverted to 3.1.0, I don't know.

**Comment by cibersheep** [comment] 2022-02-05 22:11
> [...] it should be possible to use this app as an offline-first PWA

Just for the record, there's no support for PWA on Ubuntu Touch, but webapps (sort of a contained tabs pointing to a website). But, yes, I get what you mean ;)

**Comment by Jaifroid** [comment] 2022-02-06 07:30
Tests:

- [ ] Internet Exploerer 11 from http localhost
- [ ] Internet Exploerer 11 from file system
- [ ] Firefox unpacked extension JQuery mode
- [ ] Firefox unpacked extension SW mode
- [ ] Firefox zipped unsigned extension from http://download.kiwix.org/nightly/2022-02-06/
- [ ] Edge (Chromium) extension package from http://download.kiwix.org/nightly/2022-02-06/

**Comment by Jaifroid** [comment] 2022-02-06 09:51
@mossroy Once your tests are complete, please approve or edit #805 (feel free to squash/merge it if you're happy with it, or I can). Then I think we'll be ready to create the tag.

**Comment by mossroy** [comment] 2022-02-06 13:52
Many thanks for all these tests and feedback @Jaifroid 

I managed to install the .crx on my Chromium 98 (on Ubuntu). I did a drag-and-drop of the file inside chrome://extensions/ tab (with developer mode activated)

I agree with you that we'll have to be careful before switching to SW mode by default.
And if possible find a way to warn users if some inline scripts are blocked

**Comment by mossroy** [comment] 2022-02-06 14:48
Let me know when I can create the tag

**Comment by Jaifroid** [comment] 2022-02-06 14:51
Please do, I don't have any more to do for this release. (I'm just testing the likely fix for Ubuntu touch, but as you said, that can be a v3.3.1.)

**Comment by mossroy** [comment] 2022-02-06 15:01
Release/tag created: https://github.com/kiwix/kiwix-js/releases/tag/3.3.0
But publishing the PWA did not work: https://github.com/kiwix/kiwix-js/runs/5084057842?check_suite_focus=true
I also see that there are many test versions on docker hub: https://hub.docker.com/r/kiwix/kiwix-moz-extension/tags Shouldn't they be deleted?

**Comment by Jaifroid** [comment] 2022-02-06 15:27
> Release/tag created: https://github.com/kiwix/kiwix-js/releases/tag/3.3.0 But publishing the PWA did not work: https://github.com/kiwix/kiwix-js/runs/5084057842?check_suite_focus=true I also see that there are many test versions on docker hub: https://hub.docker.com/r/kiwix/kiwix-moz-extension/tags Shouldn't they be deleted?

Hmm. I'll update it manually. Clearly tag not being picked up. I wonder why... Grrr....

**Comment by mossroy** [comment] 2022-02-06 15:29
> Hmm. I'll update it manually.


Thanks!

> Clearly tag not being picked up. I wonder why... Grrr....

No worry: it's the first time we run it on a real tag, so it's no surprise everything is not perfect on first time

**Comment by Jaifroid** [comment] 2022-02-06 15:31
The version number is still 3.3-WIP, whereas we should set it to 3.3 for release, no?
Although I thought I included code to rewrite that...

**Comment by Jaifroid** [comment] 2022-02-06 15:35
Unless we update the number, no Service Worker will detect a change. Question is, should it be updated in master when we release (I think this was my assumption, but I should have checked), or should it be updated only in the implementation. I think we need to decide the workflow here. I know we will update master to 3.4-WIP soon.

Any thoughts on how to handle this? I can se the number in the implementation arbitrarily, so it's not a big deal.

**Comment by Jaifroid** [comment] 2022-02-06 15:40
Updated manually now:

![image](https://user-images.githubusercontent.com/4304337/152688646-8c6f68d9-d907-4f7c-bccf-6c37fab65e11.png)

**Comment by mossroy** [comment] 2022-02-06 15:53
The release version number is not committed on github. The release script updates it locally before generating the packages for various targets.
I'm not very satisfied by this logic but, until we improve that, you should change this number in your script before uploading the PWA

**Comment by mossroy** [comment] 2022-02-06 15:55
> Updated manually now

Does that mean that I can upload v3.3.0 to Mozilla store?

**Comment by Jaifroid** [comment] 2022-02-06 15:59
> Does that mean that I can upload v3.3.0 to Mozilla store?

Yes, it's working fine in my Firefox Developer edition. Users who try SW mode should immediately pick up v3.3 (as they will never have accessed 3.3-WIP before). Testers who *have* accessed 3.3-WIP will see that version until they next launch the app. (This is the standard PWA self-updating flow, we can't change that, except that we could force a reload once we detect a new version, but there are pros and cons.)

**Comment by Jaifroid** [comment] 2022-02-06 16:03
> you should change this number in your script before uploading the PWA

OK. I actually have that capability in the script run by the GitHub action, but I must have assumed the versions in the files would match the tag if we are creating a release. I'll make an issue for that.

**Comment by mossroy** [comment] 2022-02-06 16:26
Uploaded on Mozilla Store, and available for Firefox users.

**Comment by Jaifroid** [comment] 2022-02-06 16:33
Nice! I was holding my breath, because I half expected some automatic error to be triggered "Apps submitted to the Extension store may not navigate programmatically...". Phew! It all seems to be working as intended, fingers crossed.

**Comment by Jaifroid** [comment] 2022-02-06 17:27
You may have noticed the PWA is set to 3.3 instead of 3.3.0. This was my mistake doing it manually (I'm so used to seeing 3.3-WIP, I just took the -WIP off). I guess it's not too important. Should I correct, or maybe we can use the 3.3.1 version as a way of testing the script (when I've done it) even if we don't update the browser extensions in the stores, just Ubuntu and the PWA?

**Comment by Jaifroid** [comment] 2022-02-06 17:44
Uploaded to Edge extension store, but they don't seem to be in a hurry... 🙀

![image](https://user-images.githubusercontent.com/4304337/152693794-b6b9d7fa-9f2d-4167-87f6-35929d11f998.png)

**Comment by mossroy** [comment] 2022-02-06 19:03
> You may have noticed the PWA is set to 3.3 instead of 3.3.0

Yes, but it's probably not a big issue. Don't bother.

**Comment by mossroy** [comment] 2022-02-06 19:15
@kelson42 : can you upload https://download.kiwix.org/nightly/2022-02-06/kiwix-chrome-unsigned-extension-3.3.0.zip on Chrome store?

**Comment by kelson42** [comment] 2022-02-06 20:44
@mossroy Submitted to review, should be published until tomorrow.

**Comment by Jaifroid** [comment] 2022-02-06 21:20
OK, it looks like the failure to update the extension PWA wasn't a problem with my workflow scripting, but a failure on the docker side. Here is the workflow:

https://github.com/kiwix/kiwix-js/runs/5084057842?check_suite_focus=true

I'd forgotten that I had in fact written code to modify the version number in the source files, and the new number is indeed set by the tag.

![image](https://user-images.githubusercontent.com/4304337/152701572-3d828c11-efdf-4a27-b176-6911818bd2d1.png)

We do know that the scripting works here, so long as VERSION was in fact set to TAG_VERSION (because we use the same scripting to set the version from the UI). Let me know if you think I need to change anything.

**Comment by mossroy** [comment] 2022-02-08 12:33
I'm wondering if it could not come from the fact that our tags are named "3.3.0", and not "v3.3.0" (which is more common).
Maybe a script removes the first character of the tag (assuming it's always the leading "v")

**Comment by mossroy** [comment] 2022-02-08 12:56
If we want to release a fix-only version 3.3.1, we might merge #818 and #827, then release a 3.3.1, before merging any other PR

**Comment by Jaifroid** [comment] 2022-02-08 21:07
@mossroy Will 3.3.1 need a changelog with the two Ubuntu Touch updates?

**Comment by mossroy** [comment] 2022-02-08 21:22
We should indeed add this version 3.3.1 to the changelog file

**Comment by mossroy** [comment] 2022-02-09 15:07
When #829 will be merged, we could merge #830 and release version 3.3.1 for all targets (not only for Ubuntu Touch)

**Comment by mossroy** [comment] 2022-02-12 12:11
I've done some basic tests on Firefox and Chromium (including as extensions), and on Firefox OS. Found no regression (risk is very low based on what has changed from 3.3.0)
I'm about to create the 3.3.1 tag.

In my opinion, we should deploy this version 3.3.1 for all platforms. The race condition might have affected some other devices we did not hear about.
The packages will be automatically generated, we only have to deploy them on the stores.

**Comment by Jaifroid** [comment] 2022-02-12 12:23
OK, fine by me! I tested on IE11 in case that's useful, and saw no regression. On IE11 it now shows the decompressors as uninitialized in the API panel, until a ZIM is loaded, at which point it populates the panel. This is simply to do with the fallback to ASM, as the WASMs get initialized (loaded) by the script, whereas ASM is just plain JS (albeit optimized). Everything works well on IE11.

**Comment by Jaifroid** [comment] 2022-02-12 12:27
This is what I mean:
IE11:
![image](https://user-images.githubusercontent.com/4304337/153711261-76192166-3cc6-4bac-ba65-f6a6d57cf548.png)

Edge:
![image](https://user-images.githubusercontent.com/4304337/153711304-f4de0eb5-6ee1-461b-abbe-0b256da967db.png)

**Comment by mossroy** [comment] 2022-02-12 12:46
OK that's fine.
I've just created tag 3.3.1, and it generated the packages in https://download.kiwix.org/nightly/2022-02-12/
I'll upload for Firefox and Ubuntu Touch

**Comment by Jaifroid** [comment] 2022-02-12 12:52
Yay, and the workflow correctly updated the PWA. Phew!

![image](https://user-images.githubusercontent.com/4304337/153712101-3777b106-3613-4993-9c67-6d935c830df2.png)

![image](https://user-images.githubusercontent.com/4304337/153712061-65cc616a-06e2-4ea8-a00d-a02777443494.png)

**Comment by mossroy** [comment] 2022-02-12 13:00
Cool for the PWA! Nice job
The 3.3.1 version is uploaded for Ubuntu Touch. @cibersheep could you check that it works well? https://open-store.io/app/kiwix
It's also available on Firefox, and its PWA has been properly updated to 3.3.1 on mine. Cool!
@kelson42 , could you upload https://download.kiwix.org/nightly/2022-02-12/kiwix-chrome-unsigned-extension-3.3.1.zip for Chrome?

**Comment by mossroy** [comment] 2022-02-12 13:02
I've unchecked what needs to be done again for 3.3.1 in the checklist of this ticket

**Comment by Jaifroid** [comment] 2022-02-12 13:48
3.3.1 uploaded to Edge store.

**Comment by kelson42** [comment] 2022-02-12 14:56
3.3.1 uploaded to Chrome store.

**Comment by kelson42** [comment] 2022-02-12 15:41
Download.kiwix.org updated with the 3 versions

**Comment by cibersheep** [comment] 2022-02-12 16:07
> Cool for the PWA! Nice job The 3.3.1 version is uploaded for Ubuntu Touch. @cibersheep could you check that it works well? https://open-store.io/app/kiwix It's also available on Firefox, and its PWA has been properly updated to 3.3.1 on mine. Cool! @kelson42 , could you upload https://download.kiwix.org/nightly/2022-02-12/kiwix-chrome-unsigned-extension-3.3.1.zip for Chrome?

I'm afraid not: `qml: [JS] (file:///opt/click.ubuntu.com/kiwix/3.3.1/www/js/lib/zstddec_wrapper.js:115) WASM failed to load, falling back to ASM... TypeError: Failed to fetch
*** Error in `webapp-container': corrupted double-linked list: 0x000000001daaa6d0 ***`

I send you a couple of logs (they might be a bit useless):

Update from test app to 3.3.1 and tried to open local zim
https://dpaste.com/FX9YH9BWE

Cleared cache:
https://dpaste.com/EHD9JRBF5

Cleared cache, uninstall, reboot phone, reinstall
https://dpaste.com/CJJWVVNQQ

Reset app from in app
https://dpaste.com/2R6LSV7C9

**Comment by Jaifroid** [comment] 2022-02-12 17:02
@cibersheep  The failure to load WASM is expected: it is supposed to fall back gracefully to ASM, and that is what was happening with the nightly, right? However, it shouldn't then error out and fail to load/display a ZIM (if I've understood correctly what is happening). Could you kindly check the last nightly that works? From http://download.kiwix.org/nightly/ . I don't see what can have changed between the last nightly that was working and release... But hopefully we can get to the bottom of it.

**Comment by Jaifroid** [comment] 2022-02-12 17:08
I wonder if these lines are significant errors caused by AppArmor policies? I'm trying to figure out if it's anything to do with APIs that are disallowed by the store... (but that run in a non-store click package)?

![image](https://user-images.githubusercontent.com/4304337/153720829-0e9f5d82-62d4-4f7b-a4ad-0bf6339fa331.png)

**Comment by cibersheep** [comment] 2022-02-12 17:19
> I wonder if these lines are significant errors caused by AppArmor policies? I'm trying to figure out if it's anything to do with APIs that are disallowed by the store... (but that run in a non-store click package)?
> 
> ![image](https://user-images.githubusercontent.com/4304337/153720829-0e9f5d82-62d4-4f7b-a4ad-0bf6339fa331.png)

The apparmor polices are how the app works on the phone itself. That have been caught but the test app as well. I'm prety sure you can ignore them

**Comment by cibersheep** [comment] 2022-02-12 17:42
Ok. I've been doing some tests. I have bad and good news:
- Non of the last versions works on my main device
- 3.3.1 works on my tablet (I had no previous versions installed before)

I'm guessing is a change in the OS of my phone?
I will ask more testers

**Comment by Jaifroid** [comment] 2022-02-12 18:09
I've created #839 to work on this. Let's continue discussion there.

**Comment by Jaifroid** [comment] 2022-02-12 18:10
We can probably close this thread. @kelson42 will you be able to do some publicity for v3.3.1?

**Closed by Jaifroid** 2022-02-12 18:10 UTC
Labels: information, tests, build
