### ISSUE TITLE
Reading a property of null in some cases in SW mode

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#520] opened 2019-06-04 19:29 UTC
When doing some tests in SW mode on Chromium, I had the following error twice : 
`Cannot read property 'documentElement' of null`
which happened on line 909 of app.js

It's a line we recently added. We also added a few null tests, but it looks like we need to add another one

![Capture du 2019-06-04 20-30-16](https://user-images.githubusercontent.com/890923/58908041-cf148b00-870f-11e9-9d96-ff5d717365d2.png)

**Comment by mossroy** [comment] 2019-06-04 19:32
I don't remember the exact scenario, but I was switching from a git branch to another branch.
I suspect it might happen when the SW has been modified, and needs to be reloaded by the browser

**Comment by Jaifroid** [comment] 2019-09-05 07:58
Unfortunately I don't think this issue is fixed. In trying to deduplicate code between app.js and service-worker.js in #556, I came across this error, and it seems reproducible on master in Chromium. I cannot reproduce the error on Edge classic or on Firefox Quantum. Therefore I believe it's a timing issue / race condition due to the way Chromium loads the Service Worker. Steps to reproduce on Chromium (running master from localhost):

**Simple version**

* Switch to Service Worker mode
* Open DevTools, load app.js if necessary
* Completely reload browser by pressing Ctrl-Shift-R inside DevTools, with DevTools open
* You should see error in screenshot below

**Steps to reproduce while completely clearing and reloading Service Worker (to be ultra-sure)**

* Switch to jQuery with DevTools shut
* Exit browser
* Open browser and go back to localhost/.../kwix-js/...
* Ensure you really are in jQuery mode, if not, repeat above, until browser opens from cold start in jQuery mode
* Open DevTools and unregister any Service Worker for kiwix-js on localhost
* Completely exit browser, re-open, open DevTools and be sure there is no SW registered
* Load app.js in DevTools if necessary, and leave it open
* Switch to Service Worker mode
* Reload browser completely with Ctrl-Shift-R while DevTools has the focus
* Error should be reproduced  

![image](https://user-images.githubusercontent.com/4304337/64319284-dcae0b00-cfb3-11e9-9661-eb5735d68318.png)

**Comment by Jaifroid** [comment] 2019-09-05 08:07
@mossroy Maybe this error could be solved with code from https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/ready , e.g.

`navigator.serviceWorker.ready.then(function(serviceWorkerRegistration) { ... });
`

**Comment by Jaifroid** [comment] 2019-09-05 08:55
OK, on https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/controller I find this:

> The controller read-only property of the ServiceWorkerContainer interface returns a ServiceWorker object if its state is activated (the same object returned by ServiceWorkerRegistration.active). **This property returns null if the request is a force refresh (Shift + refresh) or if there is no active worker**.

Doh! I guess this is to force reload of a Service Worker (?) when Devs are testing. Can we therefore ignore? It seems Chromium is the only browser written to spec here, or else I don't know how to issue a force refresh in the other browsers. I'll test a bit more to see if it's only on force refresh that the error occurs.

**Comment by mossroy** [comment] 2019-09-06 20:21
I think this is a different problem, as it's not the same variable that is null. You should open another github issue.

**Comment by Jaifroid** [comment] 2019-09-07 07:00
OK, but I think I found the cause of this error (as stated above) since it only occurs on force refresh and only in Chromium. Therefore I think it's an artefact, not a real error (or rather, it's "by design" in Chromium). If it appears in some meaningful way, I'll open an issue. For now, I'll just close this.

**Closed by Jaifroid** 2019-09-07 07:00 UTC
