### ISSUE TITLE
Missing gallery stylesheet causes incorrect display of media galleries

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#289] opened 2017-07-17 20:32 UTC
These ZIM files: 

`wikipedia_en_all_2016-12.zim` and
`wikipedia_es_all_2017-05.zim` (most likely other languages too) 

do not contain the `mediawiki.page.gallery.styles.css` stylesheet, which causes the rendering issue illustrated in the first screenshot below.

Kiwix-js [preload stylesheets branch] and kiwix-js-windows [main] now detects if the missing stylesheet is required and patches it in if the user has selected to use locally cached stylesheets. The result is the second screenshot below. Clearly this is a temporary measure, but these ZIM files will be around for a long time yet, so shipping versions of kiwix-js should attempt to render correctly.
 
Incorrectly rendered [article: "Colombia" from `wikipedia_en_all`]:

![image](https://user-images.githubusercontent.com/4304337/28287812-e79a249e-6b34-11e7-9c8e-35f83312a222.png)

Corrected:

![image](https://user-images.githubusercontent.com/4304337/28287864-136c7202-6b35-11e7-9804-c9065bbf1bd6.png)

**Comment by Jaifroid** [comment] 2017-07-18 01:34
Just a note that commit https://github.com/kiwix/kiwix-js/commit/0ff243823ac2e169cb33c2b855654db0020a879d broke reverse display of mobile-formatted ZIMs to desktop style. This has now been fixed here: https://github.com/kiwix/kiwix-js/commit/754466581703d620da043718798b4bae76bfbf84 , but the code is a bit rough and needs tidying into the transformStyles.js module.

**Comment by sharun-s** [comment] 2017-08-02 04:19
Not a good plan. This opens the door to filling the app up with every css/icon/gif file missing in every possible zim.

**Comment by Jaifroid** [comment] 2017-08-02 05:35
Hmm, well I do say it's a temporary measure, but pragmatically there's no real alternative until the ZIMs are fixed and reissued. There are a *lot* of pages on the English and Spanish Wikipedia that use this style. I don't know why it's missing from the ZIM, but it clearly causes a rendering issue which is annoying (and which I noticed almost as soon as I started using Kiwix JS). I'm running to try to get a beta of Kiwix JS UWP in the store by mid August, so I'm having to patch some things, even if not ideal. I think a major stylesheet used in a wide range of geographic and other articles is a little different from a missing icon or gif!

**Comment by kelson42** [comment] 2017-08-02 07:00
This should be reported at scrapper level, here mwoffliner.

**Comment by Jaifroid** [comment] 2017-08-02 07:20
Done: https://github.com/openzim/mwoffliner/issues/110 .

**Comment by mossroy** [comment] 2017-08-02 07:47
Thanks @Jaifroid 
Even if patching this in kiwix-js looks like a good idea, and does improve the user experience, I agree with @sharun-s that we should not try to patch the ZIM contents when they are broken.
It would be difficult to keep that as a temporary measure, as we don't know when (and if) the users will replace their ZIM file with a more recent one.
We also would need to do the same patching in other content injection modes (Service Worker etc), to avoid regressions if they become the default ones in the future.
As in #294 , I think the drawback of this issue for the user is not worth making the code more complicated.

**Comment by Jaifroid** [comment] 2017-08-02 08:23
I can definitely see the logic of this position, @mossroy . Currently the patch is only applied if a user has asked for cached stylesheets, and only if the stylesheet is required by the article. If user asks to apply the stylesheets stored in the ZIM, they will see the gallery displayed *without* the correct styling (first screenshot above). However, I'll be happy to remove this patch (it's a one-liner) if any of the css caching code is eventually adopted for kiwix-js. In the meantime, feel free to close the issue if you like.

**Comment by sharun-s** [comment] 2017-08-02 11:36
@Jaifroid cached stylesheets is a misleading phrase. I automatically assume you are talking about a performance fix when you use the word cache. It's esp confusing when the article did not have a reference or request this stylesheet! Caching isn't the right term there. So I had to spend some time scratching my head about which stylesheets/images etc you  have added for performance and which ones for other reasons. It's a bit non-obvious. Like when you say Bolivia loads 5 sheets and my zim loads only 1 I am wasting my time wondering what is going on.
 
Going forward 3 issues that need separate phrasing to avoid confusion 
1. Asset was referenced by article and a local copy is in place for performance - Cached Asset
2. Asset was referenced by article but the asset did not exist in the ZIM - Missing Asset
3. Asset was not referenced but a local copy is used to improve usability - Usability Asset
(4. maybe there are other kinds...)

In case 1&2 no good long term reasons to put the asset in the repo 
1. Browser has a cache designed to handle repeated requests to the same resources. We need to figure out how to use it. 
2. As everyone has agreed missing assets is not a kiwix-js issue but a mwoffliner issue. So no reason to fix it in kiwix-js.  
3. Usability/Transformations/Theme-ing related assets okay with me, to add to the repo in a separately marked folder just don't refer to them as cached. 
And we should be all good.

**Comment by Jaifroid** [comment] 2017-08-02 12:54
Thanks for useful terminological distinctions, @sharun-s . Will try to use them. NB, I am testing with Bolivia.html in the **Spanish** Wikipedia ZIM. This does indeed reference 5 stylesheets and a sixth is required and missing:

![image](https://user-images.githubusercontent.com/4304337/28874000-e25d5730-7787-11e7-8587-186c39617bef.png)

The problem with trying to use the browser cache for number 1 on your issue list is that we are either retrieving the stylesheet data and placing it directly in a `<style>` tag as explained in the main branch code [here](https://github.com/kiwix/kiwix-js/blob/master/www/js/app.js#L873), or else we are storing the data as a blob in RAM and, moreover, we destroy the blob as soon as possible after use to preserve the mobile browser's memory. I don't think the browser cache will be useable in either scenario.

I think a previous idea of yours -- that we automatically extract the ZIM styles on first opening a ZIM and store them in the filesystem -- is an interesting one. Main problem is whether we can get write access to the app's filesystem/storage without using native APIs. #287 (Use Apache Cordova) may help with this.

In the meantime, until we've developed that technology, there are huge performance gains to be had by using "cached assets" in the filesystem in Chrome and in Edge, and quite big gains even with Firefox. It's a choice between having people wait 36 seconds to start reading a heavy article (and sometimes crashing the app) if we don't retrieve local copies, or 6 seconds and no risk of app crash if we do...

**Comment by mossroy** [comment] 2017-08-02 13:06
I'll close this issue as "won't fix" for now, as it is initially about adding a CSS file that should be in the ZIM file.
Please create another issue if you want to discuss about caching (either with the standard browser cache, or manually on the filesystem or with any other storage API)

**Closed by mossroy** 2017-08-02 13:06 UTC
Labels: enhancement

**Comment by sharun-s** [comment] 2017-08-02 15:10
@Jaifroid Not going to open a new issue about this, but my point for someone who is looking at your code and all the css files that has been added, is distinguish between the 3 cases and document it somewhere. It's quite hard to tell which files are unreferenced injections and which ones an article has actually requested without wading through a bunch of code. 

The reason this confused me (and will confuse someone else tomorrow) is my en-wiki-2016-12 just has 1 css file (if you can believe that). You can look it up on the M/Counter article page. And I can't really remember seeing an article requesting more than 1 css file, so it felt like the regex master was going to town injecting unreferenced/usability stuff :) Sorry but I should have really clarified what zim you were using. Lesson learnt. Didn't occur to me it would be this different. Obviously I need to now start using other zim's. Anyways things make more sense now about your focus on css loading!
