### ISSUE TITLE
add preference for automatic opening of predefined local file at extension-startup

### ISSUE THREAD

**Issue by slynobody** [kiwix/kiwix-js#569] opened 2019-09-20 08:39 UTC
why always open your favorite file at startup?
could you please add a simple preference-option for automatic opening of a specific file at startup?

**Comment by kelson42** [comment] 2019-09-20 09:15
Seems similar to https://github.com/kiwix/kiwix-js/issues/561

**Comment by Jaifroid** [comment] 2019-09-20 09:54
We can add an option to load the last-visited article for a specific archive (which is #561), but the problem is that in most contexts you would still have to pick the archive. This is a limitation of JavaScript: it does not have File System access to files that the user has not explicitly picked. However, in Electron or NWJS versions of the app, there is FS access, and the archive can be re-opened automatically. @slynobody , if you are running Windows, you can try out https://github.com/kiwix/kiwix-js-windows/releases/tag/v0.9.9.93E-Standalone or https://github.com/kiwix/kiwix-js-windows/releases/tag/v0.9.9.93-IA32 for builds of Kiwix JS Windows that have the functionality you want.

I'm closing this issue, as it should be discussed in #561 or #545.

**Closed by Jaifroid** 2019-09-20 09:54 UTC
Labels: enhancement
